package br.com.cpcl.entity;

public enum ProdutoCategory {
    MERCEARIA, LATICINIOS, CARNES, FRUTAS, VEGETAIS, CONGELADOS, PADARIA, BEBIDAS,
    PRODUTOS_DE_LIMPEZA, HIGIENE_PESSOAL, UTILIDADES_DOMESTICAS
}
