package br.com.cpcl.entity;

public enum ProdutoCategory {
    NOTEBOOK, MEMORIA, MONITOR, PERIFERICOS, TV, ARMAZENAMENTO, PLACA, PROCESSADOR, COOLER, GABINETE, CABO, PASTA, LIMPEZA, FONTE, ADAPTADOR 
}
